### ISSUE TITLE
bug in params.yaml

### ISSUE THREAD

**Issue by jhennawi** [AstarVienna/skycalc_ipy#3]
I believe that the following in params.yaml should be changed

ecl_lon :
  - 135.
  - float
  - range
  - [0., 180.]
  - "[-180.0,180.0] Heliocentric ecliptic longitude"

It seems there is a typo and the [0, 180] should be [-180, 180]. This causes the example in the documentation to crash: 

skycalc.get_almanac_data(ra=83.8221, dec=-5.3911,
                             date="2018-12-06T06:00:00",
                             update_values=True)

when you try to retrieve the sky or transmission spectra. 

I'm also having problems with msolflux parameters = -1 that do not validate correctly.  I suspect it is an issue with the almanac server.

**Comment by AstarVienna** [comment]
Hi,

Sorry for the late response (on holidays), but many thanks for the bug report!
I've fixed the `ecl_lon` range. 

As for `msolflux`, why would you want a value of `-1`, when the lower possible value is `0`?

Cheers.

**Comment by jhennawi** [comment]
Right the issue is that the Almanac query is returning that value. For example: 

import skycalc_ipy
skycalc = skycalc_ipy.SkyCalc()
res=skycalc.get_almanac_data(ra=43.06933, dec=-5.05883, date="2019-08-11T09:33:29", update_values=True)
wave_sky0, sky_trans0, sky_SB0 = skycalc.get_sky_spectrum(return_type="arrays")

This crashes with the error below because ESO is I believe returning a value of -1 for msolflux. 

See <SkyCalc>.comments[<key>] for help
The following entries are invalid:
'msolflux' : -1 : Monthly Averaged Solar Flux > 0.0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-6faa46da725b> in <module>
----> 1 wave_sky0, sky_trans0, sky_SB0 = skycalc.get_sky_spectrum(return_type="arrays")

~/python/skycalc_ipy/skycalc_ipy/ui.py in get_sky_spectrum(self, return_type, filename)
    119 
    120         if not self.validate_params():
--> 121             raise ValueError("Object contains invalid parameters. "
    122                              "Not calling ESO")
    123 

ValueError: Object contains invalid parameters. Not calling ESO

**Comment by astronomyk** [comment]
Indeed it seems to be the Almanac service that is returning the `-1`

I could put a hack into skycalc_ipy, that resets all `skycalc.values["msolflux"]` to a value `>0`, but that feels to dodgy. Also, I'll likely forget about it and therefore have to go searching at some point in the future.

For now I'll add  a warning to the code example in the docs, that the user should reset the `msolflux` value before calling the `get_sky_spectrum` method:

`skycalc.values["msolflux"] = 130`

The example will now look like this:

```
import skycalc_ipy
skycalc = skycalc_ipy.SkyCalc()
res=skycalc.get_almanac_data(ra=43.06933, dec=-5.05883, date="2019-08-11T09:33:29", update_values=True)
skycalc.values["msolflux"] = 130
wave_sky0, sky_trans0, sky_SB0 = skycalc.get_sky_spectrum(return_type="arrays")
```

That said, I'm open to any other suggestions on how to deal with the alamanac return values.

Cheers,
K

**Comment by astronomyk** [comment]
New results. The Almanac service returns the expected results for dates before Jan 31, 2019. After this date, `msolflux=-1`.
Frustrating.
