### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/skycalc_ipy#31]
https://etimecalret-002.eso.org/observing/etc/
```
Websites prove their identity via certificates, which are valid for a set time period. The certificate for etimecalret-002.eso.org expired on 11/5/2023.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

Issue (re)raised at https://jira.eso.org/browse/PIPE-10404

We could consider switching to http instead of https

**Comment by hugobuddel** [comment]
Perhaps we should set an alert for early November 2024 to tell ESO that the certificate is about to expire (if it indeed almost expires)

**Comment by teutoburg** [comment]
Is this something we can do something about or does ESO have to react to this 😅
